### PCA PLOTS ###
#-----------------------------------


snps=read.table("data/raw/filtered_snps.txt",header=T)
nrow(snps)

## this snp table has ~91K rows (snps) and 53 columns.  Column names are as follows:
## Nmiss - this is just a by-product of the SNP calling pipeline.  All entries should be zero.  We can remove this column
## CHROM - chromosome (chr1-chr16 + chrmito)
## POS - position along each chromosome (non-cumulative across the genome)
## REF - reference allele (what is found in the current genome release for S288C)
## ALT - alternate allele (there is only one per SNP, all are bi-allelic)
## alt_old_01 = alt allele count in pop old_01
## N_old_01 = coverage in pop old_01
## preserve this pattern for pops old_02-old_12, then young_01-young_12

## get rid of first column
snps$Nmiss=NULL

#summarize the average coverage we achieved across all the samples (so, every other column starting column 6)
coverage=seq(6,52,2)
summary(snps[,coverage])

## mean coverage is the most useful metric here.  It seems to be lowest in pop old09 (36.28) and highest in pop young_11 (276)
## for any type of statistical analysis, it is a good idea to filter out unusually low coverage and high coverage sites.  
## This is sort of arbitrary and depends upon the dataset, but I would recommend keeping only sites that have more than 10X coverage. Anything with less is likely to give you a biased allele frequency estimate.
## You might also get rid of sites with very high coverage too, but only if they are high in relation to the mean.  For example, if some regions of the genome have very high coverage, that could indicate that there is actually a repetitive sequence that multiple reads are mapping to.  If that's the case, we would want to remove that region.

boxplot(snps[,coverage]) # from this we can see that maybe 2000 is a good cutoff for the higher end of coverage (as these look like outliers)


## filtering the dataset so that only SNPs are included that have between 10-2000X coverage.  How to do this?
## I suggest we add two columns to the dataset - one for min coverage and one for max coverage.  Then we can subset based upon this.

## calculate the min coverage per site and add it as a column
snps$mincov=apply(snps[,coverage],1,min)

## calculate the max coverage per site and add it as a column
snps$maxcov=apply(snps[,coverage],1,max)

## subset the dataset
snps2=subset(snps,mincov>10 & maxcov<2000)
## we lost nrow(snps)-nrow(snps2) = 892 SNPs.  This is hardly any, so we could consider being more aggressive in our filtering at a later time.

snps2=subset(snps,mincov>20 & maxcov<2000)  
## if we set mincov to 20, this filters out a total of 3224 sites, which is still not a lot.  So this is what I will use for now.

#now we can filter for minor allele frequency
mac=seq(5,51,2)
snps2$sum_mac=apply(snps2[,mac],1,sum)
snps2$sum_cov=apply(snps2[,coverage],1,sum)
snps2$maf=snps2$sum_mac/snps2$sum_cov

## if we filter for a minor allele frequency of 2%, that means we are getting rid of any SNP for which the less common allele is at a total frequency of 2% across all populations.
## importantly, this means we need to consider alleles with a total frequency (across all pops, this is the "maf" column) that is both greater than 2.5% and less than 97.5%.
## imposing this filter has the added benefit of getting rid of any non-polymorphic sites (these would be ones with a "maf" of zero or 1).  So it is more efficient than the previous version.

snps3=subset(snps2,maf>0.025) # this is only 93 SNPs
snps3=subset(snps3,maf<0.975) # here we lose a lot, over 17K SNPs.  So, this was an important filtering step.

## now to move on to allele frequencies.  you might want to make a new data frame with just the frequencies, or add the frequencies in as vectors to snps2.  
## I'll show you the former (more concise code compared to previous versions).

freq <- apply(snps3[,5:54],1,function(x) (x[seq(1,48,2)]/(x[seq(2,49,2)]))) 
freq2 <- t(freq)  # this transposes the new matrix
freq3 <- cbind(snps3[,1:2],freq2)  # this adds back chr and pos so that you can merge it with the original table with counts, or continue to filter it

## with this frequency table we can go ahead and run a PCA.  I'll modify it so that it accommodates the new samples

pca=prcomp(freq) ## note that this command requires a transposed matrix to work, it was generated by the code above
Population <- c(rep(paste(c("old","young"), sep=""),each=12))

pca.data <- data.frame(Sample=Population,
                       X=pca$x[,1],
                       Y=pca$x[,2],
                       Z=pca$x[,3])
pca.var <- pca$sdev^2
pca.var.per <- round(pca.var/sum(pca.var)*100, 1)

#Rearrange the order for legend
pca.data$Sample<- factor(pca.data$Sample,
                         levels = c("old","young"))

#Color palette matching replicates of each group (these are arbitrary choices)
colors=c("gold3","dodgerblue4")


pcap <- ggplot(data=pca.data, aes(x=X, y=Y,color=Sample)) +
  geom_point(size=3) +   
  scale_color_manual(name="Population",values=colors) +
  geom_point(size=3,shape=21,color="black") +  
  xlab(paste("PC1 - ", pca.var.per[1], "%", sep="")) +
  ylab(paste("PC2 - ", pca.var.per[2], "%", sep="")) +
  theme_bw()
ggtitle("")
pcap

#Make PCA plot (just plotting the first two principal components against one another)
pcap1 <- ggplot(data=pca.data, aes(x=Y, y=Z,color=Sample)) +
  geom_point(size=3) +   
  scale_color_manual(name="Population",values=colors) +
  geom_point(size=3,shape=21,color="black") +  
  xlab(paste("PC2 - ", pca.var.per[1], "%", sep="")) +
  ylab(paste("PC3 - ", pca.var.per[2], "%", sep="")) +
  theme_bw()
ggtitle("")
pcap1

jpeg(file="pca_test.jpg", units="in", height=4, width=6, res=300)
pcap1
dev.off()